version: '3'
services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    networks:
       - app-network
networks:
  app-network:
    driver: bridge